In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('flights_cleaned - flights_cleaned.csv')
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Price
0,Jet Airways,2019-01-03,Banglore,New Delhi,BLR → BOM → DEL,11:40,785,1 stop,26890
1,SpiceJet,2019-01-03,Banglore,New Delhi,BLR → HYD → DEL,15:35,485,1 stop,7744
2,Jet Airways,2019-01-03,Banglore,New Delhi,BLR → BOM → DEL,8:00,740,1 stop,27992
3,Air India,2019-01-03,Banglore,New Delhi,BLR → BOM → AMD → DEL,8:50,2345,2 stops,17135
4,Jet Airways,2019-01-03,Banglore,New Delhi,BLR → BOM → DEL,11:40,1425,1 stop,25735

In [3]:
df.shape

(10683, 9)

In [4]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Duration           0
Total_Stops        1
Price              0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(222)

In [9]:
df = df.drop_duplicates()

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.shape

(10461, 9)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10461 entries, 0 to 10682
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10461 non-null  object
 1   Date_of_Journey  10461 non-null  object
 2   Source           10461 non-null  object
 3   Destination      10461 non-null  object
 4   Route            10460 non-null  object
 5   Dep_Time         10461 non-null  object
 6   Duration         10461 non-null  int64
 7   Total_Stops      10460 non-null  object
 8   Price            10461 non-null  int64
dtypes: int64(2), object(7)
memory usage: 817.3+ KB

In [27]:
df[df['Route'].isnull()]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Price
6451,Air India,2019-06-05,Delhi,Cochin,NaN,9:45,1420,NaN,7480

In [28]:
df.loc[6451]

Airline             Air India
Date_of_Journey    2019-06-05
Source                  Delhi
Destination            Cochin
Route                     NaN
Dep_Time                 9:45
Duration                 1420
Total_Stops               NaN
Price                    7480
Name: 6451, dtype: object

In [31]:
df = df[~df['Route'].isnull()]

In [32]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Duration', 'Total_Stops', 'Price'],
      dtype='object')

In [34]:
df['Source'].value_counts()

Source
Delhi       4345
Kolkata     2860
Banglore    2177
Mumbai       697
Chennai      381
Name: count, dtype: int64

In [35]:
df['Destination'].value_counts()

Destination
Cochin       4345
Banglore     2860
Delhi        1265
New Delhi     912
Hyderabad     697
Kolkata       381
Name: count, dtype: int64

In [50]:
df['Destination'] = df['Destination'].replace('New Delhi','Delhi')

C:\Users\raush\AppData\Local\Temp\ipykernel_26372\3939513877.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Destination'] = df['Destination'].replace('New Delhi','Delhi')

In [51]:
df['Destination'].value_counts()

Destination
Cochin       4345
Banglore     2860
Delhi        2177
Hyderabad     697
Kolkata       381
Name: count, dtype: int64

In [52]:
df.sample(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Price
4661,IndiGo,2019-05-21,Delhi,Cochin,DEL → BOM → COK,17:30,480,1 stop,6794
8036,Air India,2019-06-27,Delhi,Cochin,DEL → BLR → COK,13:30,570,1 stop,8907
703,Jet Airways,2019-01-05,Banglore,Delhi,BLR → DEL,7:10,180,non-stop,7229
9892,SpiceJet,2019-12-04,Kolkata,Banglore,CCU → BLR,6:55,155,non-stop,3841
5655,Multiple carriers,2019-05-27,Delhi,Cochin,DEL → BOM → COK,9:00,720,1 stop,7886

In [53]:
df['Airline'].value_counts()

Airline
Jet Airways                          3700
IndiGo                               2043
Air India                            1694
Multiple carriers                    1196
SpiceJet                              815
Vistara                               477
Air Asia                              318
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [55]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Price
0,Jet Airways,2019-01-03,Banglore,Delhi,BLR → BOM → DEL,11:40,785,1 stop,26890
1,SpiceJet,2019-01-03,Banglore,Delhi,BLR → HYD → DEL,15:35,485,1 stop,7744
2,Jet Airways,2019-01-03,Banglore,Delhi,BLR → BOM → DEL,8:00,740,1 stop,27992
3,Air India,2019-01-03,Banglore,Delhi,BLR → BOM → AMD → DEL,8:50,2345,2 stops,17135
4,Jet Airways,2019-01-03,Banglore,Delhi,BLR → BOM → DEL,11:40,1425,1 stop,25735

# connect to MYsql

### export this dataframe into mysql

In [54]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\raush\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in c:\users\raush\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\raush\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\raush\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [58]:
from sqlalchemy import create_engine
# MySQL connection
username = "root"
password = "848163"
host = "localhost"
port = "3306"
database = "dsmp"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

table_name = 'flight' 
df.to_sql(table_name, engine, if_exists ='replace', index=False)

10460